### PR TITLE
Fix For Gnome 46

### PR DESCRIPTION
**Pull request by TaylanTatli**
Selam!

The Extension was not working for me on Gnome 46, giving a bunch of `... is not a function` errors. I managed to make it work with these changes. I wanted to let you know.

### CODE REVIEW

**Review by wwardaww — APPROVED** [review]
Thanks for contribute

**Comment by wwardaww** [comment]
hi @TaylanTatli thanks for contributing  when I check on the gnome 45 it's fail 
image
 
 So I created separate branch called `gnome46` and can you use the `dev` branch for development  for further changes

**Comment by TaylanTatli** [comment]
I'm on 46, so I don't know why it's not working on 45. Is there any error output?

**Comment by wwardaww** [comment]
no, there is no error output. Actually its working but for some reason the scroll view doesn't work the same as gn45

**Pull request merged**
